// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHox1L_A_Sg1AvqwMFVT1iDsnsaSKTaXM',
    appId: '1:195625693187:web:3a434c9fa938a5486f5e36',
    messagingSenderId: '195625693187',
    projectId: 'mindsaarthi-150df',
    authDomain: 'mindsaarthi-150df.firebaseapp.com',
    storageBucket: 'mindsaarthi-150df.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0BCBAnzGXqqFNNLR-HXsQ0mMSmcdabtA',
    appId: '1:195625693187:android:70ce27d21622ce7b6f5e36',
    messagingSenderId: '195625693187',
    projectId: 'mindsaarthi-150df',
    storageBucket: 'mindsaarthi-150df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVtP9FBqQgdsXb17AJTaZi6uhUMDgrDu8',
    appId: '1:195625693187:ios:b0186f4cc28d22716f5e36',
    messagingSenderId: '195625693187',
    projectId: 'mindsaarthi-150df',
    storageBucket: 'mindsaarthi-150df.firebasestorage.app',
    iosBundleId: 'com.example.mindsaarthiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHox1L_A_Sg1AvqwMFVT1iDsnsaSKTaXM',
    appId: '1:195625693187:web:340fa17c30c4ce2b6f5e36',
    messagingSenderId: '195625693187',
    projectId: 'mindsaarthi-150df',
    authDomain: 'mindsaarthi-150df.firebaseapp.com',
    storageBucket: 'mindsaarthi-150df.firebasestorage.app',
  );
}
